import {test,expect} from '@playwright/test';
test('only owner email switches to passwordless admin sign-in',async({page})=>{
 let verified=false;let requests=0;
 const owner={id:'owner',email:'dibyendukoley50@gmail.com',name:'Owner',role:'admin',email_verified:true};
 await page.route('**/api/v1/auth/session',r=>r.fulfill({json:{user:verified?owner:null,csrf_token:'qa-csrf'}}));
 await page.route('**/api/v1/auth/admin-email-code',r=>{
   requests++;expect(r.request().postDataJSON()).toEqual({email:owner.email});
   return r.fulfill({json:{otp_required:true,email:owner.email,csrf_token:'qa-csrf'}});
 });
 await page.route('**/api/v1/auth/verify-login-code',r=>{verified=true;return r.fulfill({json:{user:owner,csrf_token:'qa-csrf'}});});
 await page.goto('/login');
 await expect(page.getByLabel('Password',{exact:true})).toBeVisible();
 await page.getByLabel('Email',{exact:true}).fill(owner.email);
 await expect(page.getByLabel('Password',{exact:true})).toHaveCount(0);
 await expect(page.getByText('Forgot your password?')).toHaveCount(0);
 await page.getByLabel('Email',{exact:true}).fill('normal@example.org');
 await expect(page.getByLabel('Password',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Create a citizen account'}).click();
 await expect(page.getByLabel('Full Name')).toBeVisible();
 await expect(page.getByLabel('Password',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Already have an account? Sign in'}).click();
 await page.getByLabel('Email',{exact:true}).fill(owner.email);
 await page.getByRole('button',{name:'Send verification code'}).click();
 await page.getByLabel('Email verification code').fill('123456');
 await page.getByRole('button',{name:'Verify and sign in'}).click();
 await expect(page).toHaveURL(/\/admin$/);expect(requests).toBe(1);
});
test('email code step supports retry, resend and completed sign-in',async({page})=>{
 let verified=false;
 const user={id:'qa-email-user',name:'Email QA',email:'qa@example.org',role:'citizen',username:'email_qa',email_verified:true};
 await page.route('https://tile.openstreetmap.org/**',r=>r.abort());
 await page.route('**/api/v1/auth/session',r=>r.fulfill({json:{user:verified?user:null,csrf_token:'qa-csrf'}}));
 await page.route('**/api/v1/auth/login',r=>r.fulfill({json:{otp_required:true,email:'qa@example.org',csrf_token:'qa-csrf'}}));
 await page.route('**/api/v1/auth/resend-login-code',r=>r.fulfill({json:{otp_required:true}}));
 await page.route('**/api/v1/auth/verify-login-code',r=>{if(r.request().postDataJSON().code!=='123456')return r.fulfill({status:422,json:{detail:'Incorrect verification code.'}});verified=true;return r.fulfill({json:{user,csrf_token:'qa-csrf'}})});
 await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill('qa@example.org');await page.getByLabel('Password',{exact:true}).fill('QaPassword123!');await page.getByRole('button',{name:'Sign in',exact:true}).click();
 const code=page.getByLabel('Email verification code');await expect(code).toBeVisible();await code.fill('000000');await page.getByRole('button',{name:'Verify and sign in'}).click();await expect(page.getByRole('alert')).toHaveText('Incorrect verification code.');
 await page.getByRole('button',{name:'Resend code'}).click();await expect(page.getByText('A new code has been queued. Use the latest email.')).toBeVisible();await code.fill('123456');await page.getByRole('button',{name:'Verify and sign in'}).click();await expect(page).toHaveURL(/explore/);
});
test('cleanup sign-in switches an existing citizen session to admin OTP and records',async({page})=>{
 let verified=false;
 const citizen={id:'citizen',name:'Citizen',email:'citizen@example.org',role:'citizen'};
 const owner={id:'owner',name:'Owner',email:'dibyendukoley50@gmail.com',role:'admin'};
 await page.route('**/api/v1/auth/session',r=>r.fulfill({json:{user:verified?owner:citizen,csrf_token:'test'}}));
 await page.route('**/api/v1/auth/admin-email-code',r=>r.fulfill({json:{email:owner.email,otp_required:true,csrf_token:'test'}}));
 await page.route('**/api/v1/auth/verify-login-code',r=>{verified=true;return r.fulfill({json:{user:owner,csrf_token:'test'}});});
 await page.route('**/api/v1/admin/records/summary',r=>r.fulfill({json:{counts:{accounts:2,reports:1,waterbodies:7}}}));
 await page.route('**/api/v1/admin/records?*',r=>r.fulfill({json:{items:[{id:'report-test',name:'Demo lake',detail:'Saved observation',status:'new',created_at:'2026-10-05T00:00:00Z',case_id:'case-test'}],total:1,page_size:25}}));
 await page.goto('/admin/cleanup');
 await page.getByRole('link',{name:'Sign in as administrator'}).click();
 await expect(page.getByRole('heading',{name:'Administrator sign-in',exact:true})).toBeVisible();
 await expect(page.getByLabel('Password',{exact:true})).toHaveCount(0);
 await expect(page.getByRole('link',{name:'Explore waters'})).toHaveCount(0);
 await page.getByRole('button',{name:'Send verification code'}).click();
 await page.getByLabel('Email verification code').fill('123456');
 await page.getByRole('button',{name:'Verify and sign in'}).click();
 await expect(page).toHaveURL(/\/admin$/);
 await expect(page.getByRole('heading',{name:'Database & records'})).toBeVisible();
 await expect(page.getByText('Saved observation')).toBeVisible();
 await expect(page.getByRole('link',{name:'Prototype data cleanup'})).toBeVisible();
 await page.goto('/workspace');
 await expect(page.getByRole('heading',{name:'Database & records'})).toBeVisible();
});
