"""Repeat-safe synthetic district seed. Never resets arbitrary application data."""
import argparse
import os
from datetime import datetime
from functools import lru_cache
from sqlalchemy import select
from .auth import hasher
from .models import *
from .db import Base, engine, SessionLocal

@lru_cache(maxsize=1)
def demo_password():
    return hasher.hash("DemoPass123!")

def seed(db):
    if db.get(WaterBody,"wb-reedwater"):
        if not db.get(Connector,"con-demo-source"):
            db.add(Connector(id="con-demo-source",organisation_id="org-reedwatch",name="Demo scenario source",kind="demo_fixture",state="configured",config={"fixture_state":"healthy"},data={"synthetic":True,"notice":"Local synthetic demo scenario; no external partner."}))
            db.commit()
        closure=db.get(Event,"event-closure")
        if closure and closure.synthetic and closure.case_id=="case-historical" and not closure.data.get("outcome"):
            closure.data={**closure.data,"outcome":"Documented cleanup and follow-up complete; environmental condition not assessed.","outcome_category":"action_documented_completed","completed_at":"2026-05-15T08:00:00+00:00","supporting_record":"action-followup"}
            db.commit()
        return
    date="2026-01-01T00:00:00+00:00"
    orgs=[Organisation(id="org-reedwatch",name="Demo Reedwatch Collective",description="Fictional field group contributing demonstration records and coordinating assigned cases.",contact="demo-contact@aquarelay.local",synthetic=True,created_at=date,data={"verification":"Demo identity — no official verification or partnership","responsibility_source":"source-district"}),Organisation(id="org-district",name="Demo District Water Office",description="Fictional case-handling organisation for the demonstration district.",contact="demo-office@aquarelay.local",synthetic=True,created_at=date,data={"verification":"Synthetic organisation — not a public authority"}),Organisation(id="org-research",name="Demo Freshwater Research Circle",description="Fictional research contributors with scoped record-review roles.",contact="demo-research@aquarelay.local",synthetic=True,created_at=date)]
    db.add_all(orgs); db.flush()
    users=[User(id="user-citizen",name="Demo Citizen",email="citizen@demo.aquarelay.local",password_hash=demo_password(),role="citizen",created_at=date),User(id="user-manager",name="Demo Reedwatch Manager",email="manager@demo.aquarelay.local",password_hash=demo_password(),role="manager",organisation_id="org-reedwatch",created_at=date),User(id="user-other",name="Demo District Manager",email="other@demo.aquarelay.local",password_hash=demo_password(),role="manager",organisation_id="org-district",created_at=date),User(id="user-researcher",name="Demo Research Reviewer",email="researcher@demo.aquarelay.local",password_hash=demo_password(),role="researcher",organisation_id="org-research",created_at=date)]
    db.add_all(users); db.flush()
    db.add_all([Membership(id="member-manager",user_id="user-manager",organisation_id="org-reedwatch",role="manager",created_at=date),Membership(id="member-other",user_id="user-other",organisation_id="org-district",role="manager",created_at=date),Membership(id="member-research",user_id="user-researcher",organisation_id="org-research",role="contributor",created_at=date)])
    fixtures=[("reedwater","Demo Reedwater Lake","lake",77.587,12.979,"Reedwater Quarter","A synthetic lake with community observations, a documented response, and a preserved case history."),("millbank","Demo Millbank Canal","canal",77.594,12.974,"Millbank Ward","A fictional canal with a recorded floating-waste observation under investigation."),("willow","Demo Willow Pond","pond",77.578,12.970,"Willow Gardens","A demonstration pond with biodiversity records. Its environmental condition has not been assessed."),("eastmere","Demo Eastmere Lake","lake",77.609,12.982,"Eastmere Ward","Synthetic monitoring records link a demonstration field dataset to this lake."),("lantern","Demo Lantern Stream","stream",77.600,12.963,"Lantern Walk","A fictional stream with a documented waterway link. Nearby distance alone does not establish a connection."),("orchard","Demo Orchard Pool","pond",77.570,12.981,"Orchard Quarter","A demonstration pond with limited records. Missing observations do not imply safe water."),("northfen","Demo North Fen","wetland",77.599,12.991,"North Fen Ward","A synthetic wetland with coarse biodiversity locations and an outdated source context.")]
    for key,name,kind,lon,lat,locality,summary in fixtures:
        if kind in {"stream","canal"}:
            geometry={"type":"LineString","coordinates":[[lon-.003,lat-.002],[lon-.001,lat],[lon+.001,lat+.001],[lon+.004,lat+.003]]}
        else:
            geometry={"type":"Polygon","coordinates":[[[lon-.002,lat-.001],[lon-.001,lat+.002],[lon+.001,lat+.002],[lon+.0025,lat],[lon+.001,lat-.0015],[lon-.002,lat-.001]]]}
        db.add(WaterBody(id="wb-"+key,name=name,aliases=[key.title(),name.replace("Demo ","")],type=kind,locality=locality,latitude=lat,longitude=lon,geometry=geometry,summary=summary,synthetic=True,created_at=date,data={"responsible_organisation_id":"org-district" if key=="millbank" else "org-reedwatch","geometry_notice":"Fictional coordinates and geometry; not verified geography."}))
    db.flush()
    connector=Connector(id="con-demo-sensor",organisation_id="org-reedwatch",name="Demo Reedwater sensor subset",kind="sensorthings",state="disabled",created_at=date,data={"synthetic":True,"notice":"Configure an allowed endpoint before live sync. No live municipal connection."})
    db.add(connector)
    db.add(Connector(id="con-demo-source",organisation_id="org-reedwatch",name="Demo scenario source",kind="demo_fixture",state="configured",created_at=date,config={"fixture_state":"healthy"},data={"synthetic":True,"notice":"Local synthetic source scenario. Test connection returns real staged records; failure/recovery are explicitly demo simulations."}))
    db.flush()
    db.add_all([Source(id="source-district",waterbody_id="wb-reedwater",organisation_id="org-reedwatch",name="Synthetic district registry",kind="registry",license="CC0-1.0",attribution="AquaRelay authored synthetic fixtures",observed_at=date,source_updated_at=date,synthetic=True,created_at=date),Source(id="source-field",waterbody_id="wb-reedwater",organisation_id="org-reedwatch",name="Demo field observation notebook",kind="field_notebook",license="CC0-1.0",attribution="Synthetic demonstration observations; not field measurements",observed_at="2026-09-25T06:00:00+00:00",source_updated_at="2026-09-25T07:00:00+00:00",synthetic=True,created_at=date),Source(id="source-biodiversity",waterbody_id="wb-willow",organisation_id="org-research",name="Demo biodiversity notebook",kind="research",license="CC0-1.0",attribution="Synthetic species records authored for the demonstration",observed_at="2026-09-20T05:30:00+00:00",synthetic=True,created_at=date),Source(id="source-waterway",waterbody_id="wb-lantern",organisation_id="org-district",name="Demo waterway connection note",kind="document",license="CC0-1.0",attribution="Fictional waterway connection documentation",observed_at=date,synthetic=True,created_at=date),Source(id="source-millbank",waterbody_id="wb-millbank",organisation_id="org-district",name="Demo canal inspection log",kind="field_notebook",license="CC0-1.0",attribution="Synthetic inspection log",observed_at="2026-09-23T09:00:00+00:00",synthetic=True,created_at=date),Source(id="source-northfen",waterbody_id="wb-northfen",organisation_id="org-research",name="Demo archival wetland dataset",kind="dataset",license="CC0-1.0",attribution="Synthetic archival measurements",state="stale",observed_at="2025-10-02T08:00:00+00:00",synthetic=True,created_at=date)])
    db.flush()
    db.add_all([MonitoringSite(id="site-reedwater-bank",waterbody_id="wb-reedwater",name="Demo west-bank sampling point",latitude=12.979,longitude=77.587,source_id="source-field",created_at=date),Observation(id="obs-temperature",waterbody_id="wb-reedwater",source_id="source-field",external_id="demo-temp-001",parameter="temperature",value=24.2,unit="Cel",observed_at="2026-09-25T06:00:00+00:00",received_at="2026-09-25T07:00:00+00:00",synthetic=True,created_at="2026-09-25T07:00:00+00:00",data={"site_id":"site-reedwater-bank"}),Observation(id="obs-ph",waterbody_id="wb-reedwater",source_id="source-field",external_id="demo-ph-001",parameter="ph",value=7.1,unit="1",observed_at="2026-09-25T06:00:00+00:00",synthetic=True,created_at="2026-09-25T07:00:00+00:00"),Observation(id="obs-eastmere",waterbody_id="wb-eastmere",source_id="source-field",external_id="demo-east-temp-001",parameter="temperature",value=23.8,unit="Cel",observed_at="2026-09-24T06:00:00+00:00",synthetic=True,created_at="2026-09-24T07:00:00+00:00"),Biodiversity(id="bio-heron",waterbody_id="wb-reedwater",source_id="source-biodiversity",common_name="Demo heron observation",scientific_name="Ardeidae (family)",observed_at="2026-09-20T05:30:00+00:00",synthetic=True,created_at="2026-09-20T06:00:00+00:00"),Biodiversity(id="bio-dragonfly",waterbody_id="wb-willow",source_id="source-biodiversity",common_name="Demo dragonfly observation",scientific_name="Anisoptera (infraorder)",observed_at="2026-09-20T05:30:00+00:00",restricted=True,synthetic=True,created_at="2026-09-20T06:00:00+00:00")])
    db.add_all([Case(id="case-historical",waterbody_id="wb-reedwater",organisation_id="org-reedwatch",title="Demo shoreline waste observation",description="Demo scenario: scattered shoreline waste was recorded. A cleanup and follow-up were documented. No ecological recovery conclusion is recorded.",state="closed",review_state="reviewed",observed_at="2026-04-12T07:00:00+00:00",created_at="2026-04-12T08:00:00+00:00",synthetic=True,data={"outcome":"Documented cleanup and follow-up complete; environmental condition not assessed.","completed_at":"2026-05-15T08:00:00+00:00","supporting_record":"action-followup"}),Case(id="case-current",waterbody_id="wb-reedwater",organisation_id="org-reedwatch",title="Demo fish mortality observation",description="Community report of approximately 5–10 fish. This synthetic observation has not yet been reviewed; cause is unknown.",state="new",review_state="unreviewed",observed_at="2026-09-28T04:30:00+00:00",created_at="2026-09-28T05:00:00+00:00",synthetic=True),Case(id="case-millbank",waterbody_id="wb-millbank",organisation_id="org-district",title="Demo floating waste observation",description="Demo inspection records floating waste. An investigation is documented; no environmental cause or safety finding is recorded.",state="investigating",review_state="reviewed",observed_at="2026-09-23T09:00:00+00:00",created_at="2026-09-23T10:00:00+00:00",synthetic=True)])
    db.flush()
    db.add_all([Report(id="report-current",user_id="user-citizen",client_id="seed-current-report",waterbody_id="wb-reedwater",case_id="case-current",observation_type="fish_mortality",description="Synthetic fish mortality observation. Cause unknown; not yet reviewed.",observed_at="2026-09-28T04:30:00+00:00",received_at="2026-09-28T05:00:00+00:00",count_estimate="5–10",language="English",synthetic=True,created_at="2026-09-28T05:00:00+00:00"),Action(id="action-cleanup",case_id="case-historical",waterbody_id="wb-reedwater",organisation_id="org-reedwatch",title="Demo shoreline cleanup documented",description="Demo scenario: shoreline waste collection was documented. Cleanup does not establish ecological restoration.",completed_at="2026-05-01T08:00:00+00:00",synthetic=True,created_at="2026-05-01T09:00:00+00:00"),Action(id="action-followup",case_id="case-historical",waterbody_id="wb-reedwater",organisation_id="org-reedwatch",title="Demo follow-up visit recorded",description="Demo scenario: follow-up documentation completed. Water safety and ecological condition were not assessed.",completed_at="2026-05-14T08:00:00+00:00",synthetic=True,created_at="2026-05-14T09:00:00+00:00")])
    db.flush()
    timeline=[("event-historical-report","case-historical","report","Demo shoreline waste reported","Community observation recorded in the synthetic district.","2026-04-12T08:00:00+00:00","new"),("event-historical-investigate","case-historical","case_update","Demo investigation recorded","Synthetic investigation note; no causal conclusion.","2026-04-20T08:00:00+00:00","investigating"),("event-cleanup","case-historical","action","Demo cleanup documented","Waste collection documented. Ecosystem restoration was not assessed.","2026-05-01T09:00:00+00:00","action_in_progress"),("event-followup","case-historical","action","Demo follow-up recorded","Follow-up visit documented without inferring recovery.","2026-05-14T09:00:00+00:00","action_in_progress"),("event-closure","case-historical","closure","Demo case closed with documented outcome","Closure records the response documentation; environmental condition remains unassessed.","2026-05-15T08:00:00+00:00","closed"),("event-current-report","case-current","report","Community report — not yet reviewed","Synthetic fish mortality report received. Cause unknown.","2026-09-28T05:00:00+00:00","new")]
    for i,(eid,cid,kind,title,description,when,state) in enumerate(timeline):
        event_data={"state":state}
        if kind=="closure": event_data.update(outcome="Documented cleanup and follow-up complete; environmental condition not assessed.",outcome_category="action_documented_completed",completed_at=when,supporting_record="action-followup")
        db.add(Event(id=eid,sequence=int(datetime.fromisoformat(when).timestamp()*1e6)+i,waterbody_id="wb-reedwater",case_id=cid,kind=kind,title=title,description=description,actor_id="user-manager",source_id="source-field",synthetic=True,created_at=when,data=event_data))
    db.add_all([Relationship(id="relationship-reedwatch",waterbody_id="wb-reedwater",target_type="organisation",target_id="org-reedwatch",kind="documented_responsibility",description="Demo registry assigns case coordination to the fictional Reedwatch Collective; no real-world authority claim.",source_id="source-district",synthetic=True,created_at=date),Relationship(id="relationship-millbank",waterbody_id="wb-reedwater",target_type="waterbody",target_id="wb-millbank",kind="documented_waterway",description="Synthetic district note documents a fictional outflow link to Millbank Canal; this is not inferred from proximity.",source_id="source-waterway",synthetic=True,created_at=date),Relationship(id="relationship-lantern",waterbody_id="wb-lantern",target_type="waterbody",target_id="wb-millbank",kind="documented_waterway",description="Fictional district waterway link supported by the demo connection note.",source_id="source-waterway",synthetic=True,created_at=date)])
    db.commit()

if __name__=="__main__":
    parser=argparse.ArgumentParser(description="Seed AquaRelay synthetic demonstration records. Repeat-safe; no deletion.")
    parser.parse_args()
    if os.getenv("DEMO_MODE","true").lower()!="true":
        print("DEMO_MODE=false: synthetic seed disabled. No data changed.")
    else:
        Base.metadata.create_all(engine)
        with SessionLocal() as db:
            seed(db)
        print("Synthetic district seeded (or already present). No existing records deleted.")


