"""canonical relational baseline"""
from alembic import op
import sqlalchemy as sa

revision = '1f3029b64e19'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.String(length=40), nullable=False),
    sa.Column('locked_at', sa.String(length=40), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_table('organisations',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisations_created_at'), 'organisations', ['created_at'], unique=False)
    op.create_table('waterbodies',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('locality', sa.String(length=160), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waterbodies_created_at'), 'waterbodies', ['created_at'], unique=False)
    op.create_table('cases',
    sa.Column('waterbody_id', sa.String(length=80), nullable=False),
    sa.Column('organisation_id', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('review_state', sa.String(length=40), nullable=False),
    sa.Column('delivery_state', sa.String(length=40), nullable=False),
    sa.Column('observed_at', sa.String(length=40), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_organisation_id'), 'cases', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_cases_waterbody_id'), 'cases', ['waterbody_id'], unique=False)
    op.create_table('connectors',
    sa.Column('organisation_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.Column('last_attempt_at', sa.String(length=40), nullable=True),
    sa.Column('last_success_at', sa.String(length=40), nullable=True),
    sa.Column('last_observed_at', sa.String(length=40), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectors_created_at'), 'connectors', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('organisation_id', sa.String(length=80), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_table('evidence_requests',
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('organisation_id', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_requests_created_at'), 'evidence_requests', ['created_at'], unique=False)
    op.create_table('mapping_versions',
    sa.Column('connector_id', sa.String(length=80), nullable=True),
    sa.Column('organisation_id', sa.String(length=80), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_hash', sa.String(length=64), nullable=True),
    sa.Column('schema_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_versions_created_at'), 'mapping_versions', ['created_at'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('organisation_id', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organisation_id')
    )
    op.create_index(op.f('ix_memberships_created_at'), 'memberships', ['created_at'], unique=False)
    op.create_table('moderation',
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_created_at'), 'moderation', ['created_at'], unique=False)
    op.create_table('notes',
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('organisation_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_created_at'), 'notes', ['created_at'], unique=False)
    op.create_table('receipts',
    sa.Column('waterbody_id', sa.String(length=80), nullable=True),
    sa.Column('connector_id', sa.String(length=80), nullable=True),
    sa.Column('organisation_id', sa.String(length=80), nullable=True),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_receipts_created_at'), 'receipts', ['created_at'], unique=False)
    op.create_table('reports',
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('waterbody_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('observation_type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.String(length=40), nullable=False),
    sa.Column('received_at', sa.String(length=40), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('count_estimate', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=80), nullable=True),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_report_replay')
    )
    op.create_index(op.f('ix_reports_case_id'), 'reports', ['case_id'], unique=False)
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=True),
    sa.Column('expires_at', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessions_created_at'), 'sessions', ['created_at'], unique=False)
    op.create_table('sources',
    sa.Column('waterbody_id', sa.String(length=80), nullable=True),
    sa.Column('organisation_id', sa.String(length=80), nullable=True),
    sa.Column('connector_id', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('license', sa.String(length=120), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.String(length=40), nullable=True),
    sa.Column('received_at', sa.String(length=40), nullable=True),
    sa.Column('source_updated_at', sa.String(length=40), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_created_at'), 'sources', ['created_at'], unique=False)
    op.create_index(op.f('ix_sources_waterbody_id'), 'sources', ['waterbody_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('waterbody_id', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius_m', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'waterbody_id', name='uq_follow')
    )
    op.create_index(op.f('ix_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_table('biodiversity',
    sa.Column('waterbody_id', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=False),
    sa.Column('common_name', sa.String(length=160), nullable=False),
    sa.Column('scientific_name', sa.String(length=160), nullable=True),
    sa.Column('observed_at', sa.String(length=40), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biodiversity_created_at'), 'biodiversity', ['created_at'], unique=False)
    op.create_index(op.f('ix_biodiversity_waterbody_id'), 'biodiversity', ['waterbody_id'], unique=False)
    op.create_table('events',
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('waterbody_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=True),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_case_id'), 'events', ['case_id'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_sequence'), 'events', ['sequence'], unique=True)
    op.create_index(op.f('ix_events_waterbody_id'), 'events', ['waterbody_id'], unique=False)
    op.create_table('evidence',
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=True),
    sa.Column('report_id', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('original_path', sa.Text(), nullable=False),
    sa.Column('public_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_created_at'), 'evidence', ['created_at'], unique=False)
    op.create_table('import_runs',
    sa.Column('connector_id', sa.String(length=80), nullable=True),
    sa.Column('organisation_id', sa.String(length=80), nullable=True),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('mapping_version_id', sa.String(length=80), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('approved_at', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['mapping_version_id'], ['mapping_versions.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_runs_created_at'), 'import_runs', ['created_at'], unique=False)
    op.create_table('monitoring_sites',
    sa.Column('waterbody_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_sites_created_at'), 'monitoring_sites', ['created_at'], unique=False)
    op.create_index(op.f('ix_monitoring_sites_waterbody_id'), 'monitoring_sites', ['waterbody_id'], unique=False)
    op.create_table('observations',
    sa.Column('waterbody_id', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('parameter', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('unit', sa.String(length=80), nullable=True),
    sa.Column('observed_at', sa.String(length=40), nullable=False),
    sa.Column('received_at', sa.String(length=40), nullable=True),
    sa.Column('source_updated_at', sa.String(length=40), nullable=True),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', 'parameter', name='uq_source_observation')
    )
    op.create_index(op.f('ix_observations_created_at'), 'observations', ['created_at'], unique=False)
    op.create_index(op.f('ix_observations_observed_at'), 'observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_observations_source_id'), 'observations', ['source_id'], unique=False)
    op.create_index(op.f('ix_observations_waterbody_id'), 'observations', ['waterbody_id'], unique=False)
    op.create_table('relationships',
    sa.Column('waterbody_id', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_created_at'), 'relationships', ['created_at'], unique=False)
    op.create_index(op.f('ix_relationships_waterbody_id'), 'relationships', ['waterbody_id'], unique=False)
    op.create_table('actions',
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('waterbody_id', sa.String(length=80), nullable=False),
    sa.Column('organisation_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.String(length=40), nullable=False),
    sa.Column('evidence_id', sa.String(length=80), nullable=True),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_case_id'), 'actions', ['case_id'], unique=False)
    op.create_index(op.f('ix_actions_created_at'), 'actions', ['created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('waterbody_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('available_at', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_notification_dedup')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_actions_created_at'), table_name='actions')
    op.drop_index(op.f('ix_actions_case_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_relationships_waterbody_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_created_at'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_observations_waterbody_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_source_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_observed_at'), table_name='observations')
    op.drop_index(op.f('ix_observations_created_at'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_monitoring_sites_waterbody_id'), table_name='monitoring_sites')
    op.drop_index(op.f('ix_monitoring_sites_created_at'), table_name='monitoring_sites')
    op.drop_table('monitoring_sites')
    op.drop_index(op.f('ix_import_runs_created_at'), table_name='import_runs')
    op.drop_table('import_runs')
    op.drop_index(op.f('ix_evidence_created_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_events_waterbody_id'), table_name='events')
    op.drop_index(op.f('ix_events_sequence'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index(op.f('ix_events_case_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_biodiversity_waterbody_id'), table_name='biodiversity')
    op.drop_index(op.f('ix_biodiversity_created_at'), table_name='biodiversity')
    op.drop_table('biodiversity')
    op.drop_index(op.f('ix_subscriptions_created_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_sources_waterbody_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_created_at'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_sessions_created_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_case_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_receipts_created_at'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_notes_created_at'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_moderation_created_at'), table_name='moderation')
    op.drop_table('moderation')
    op.drop_index(op.f('ix_memberships_created_at'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_mapping_versions_created_at'), table_name='mapping_versions')
    op.drop_table('mapping_versions')
    op.drop_index(op.f('ix_evidence_requests_created_at'), table_name='evidence_requests')
    op.drop_table('evidence_requests')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_connectors_created_at'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_index(op.f('ix_cases_waterbody_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_organisation_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_waterbodies_created_at'), table_name='waterbodies')
    op.drop_table('waterbodies')
    op.drop_index(op.f('ix_organisations_created_at'), table_name='organisations')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
